In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6,7,8,9]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
l1 = [4,5,6,7,'nagesh',34.57,True]

In [10]:
a1= np.array(l1)

In [11]:
a2= np.array([[1,2,3],[4,5,6]])

In [12]:
a3= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
a1

array(['4', '5', '6', '7', 'nagesh', '34.57', 'True'], dtype='<U32')

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
a1.ndim # array_name.ndim gives diamension of array

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [19]:
a1.size # size gives you total number of elements in array

7

In [20]:
a2.size

6

In [21]:
a3.size

9

In [22]:
a1.shape  # one diamention meaans value of x in graph

(7,)

In [23]:
a2.shape # two diamention x= 3 and y = 2

(2, 3)

In [24]:
a3.shape # three diamention  x=3 , y=3, z=1

(1, 3, 3)

In [28]:
np.random.randint(2,5)

2

In [30]:
np.random.randint(2,50) # this generate the numbers in beteen 2 to 50 randomly

35

In [31]:
np.random.randint(2,50, (3,4)) # it generate 3 columns and 4 rows

array([[41, 42, 47, 26],
       [25, 29, 27,  2],
       [30, 35, 27, 34]])

In [32]:
np.random.randint(2,50, (2,3,4)) # thee diamention array with random values

array([[[19, 20, 42, 13],
        [38, 14, 28, 40],
        [40, 31,  5, 26]],

       [[43, 22,  4, 46],
        [34, 12,  4, 34],
        [31, 43, 23, 28]]])

In [33]:
np.random.rand(2,3)

array([[0.19696444, 0.98405405, 0.29070212],
       [0.42545039, 0.50338694, 0.97159228]])

In [35]:
a4 = np.random.randn(4,4) # it gives normal distribution data

In [36]:
a4

array([[-0.09277332, -0.39922445, -0.87079802,  0.97532473],
       [-0.09171193,  0.16879142, -0.97528774, -1.20683175],
       [-1.12968683, -0.99997113,  1.3143284 , -0.2297609 ],
       [ 0.41114112, -0.46427738, -0.61632191,  0.4388022 ]])

In [37]:
a4.reshape(8,2) # it reshape the array containg same number of data

array([[-0.09277332, -0.39922445],
       [-0.87079802,  0.97532473],
       [-0.09171193,  0.16879142],
       [-0.97528774, -1.20683175],
       [-1.12968683, -0.99997113],
       [ 1.3143284 , -0.2297609 ],
       [ 0.41114112, -0.46427738],
       [-0.61632191,  0.4388022 ]])

In [38]:
a4.reshape(2,8)

array([[-0.09277332, -0.39922445, -0.87079802,  0.97532473, -0.09171193,
         0.16879142, -0.97528774, -1.20683175],
       [-1.12968683, -0.99997113,  1.3143284 , -0.2297609 ,  0.41114112,
        -0.46427738, -0.61632191,  0.4388022 ]])

In [39]:
a4.reshape(16,1)

array([[-0.09277332],
       [-0.39922445],
       [-0.87079802],
       [ 0.97532473],
       [-0.09171193],
       [ 0.16879142],
       [-0.97528774],
       [-1.20683175],
       [-1.12968683],
       [-0.99997113],
       [ 1.3143284 ],
       [-0.2297609 ],
       [ 0.41114112],
       [-0.46427738],
       [-0.61632191],
       [ 0.4388022 ]])

In [40]:
a4.reshape(2,-1) # any -ve it will take atomatically 

array([[-0.09277332, -0.39922445, -0.87079802,  0.97532473, -0.09171193,
         0.16879142, -0.97528774, -1.20683175],
       [-1.12968683, -0.99997113,  1.3143284 , -0.2297609 ,  0.41114112,
        -0.46427738, -0.61632191,  0.4388022 ]])

In [41]:
a4.reshape(2,-9)

array([[-0.09277332, -0.39922445, -0.87079802,  0.97532473, -0.09171193,
         0.16879142, -0.97528774, -1.20683175],
       [-1.12968683, -0.99997113,  1.3143284 , -0.2297609 ,  0.41114112,
        -0.46427738, -0.61632191,  0.4388022 ]])

In [42]:
a4.reshape(2,2,4)

array([[[-0.09277332, -0.39922445, -0.87079802,  0.97532473],
        [-0.09171193,  0.16879142, -0.97528774, -1.20683175]],

       [[-1.12968683, -0.99997113,  1.3143284 , -0.2297609 ],
        [ 0.41114112, -0.46427738, -0.61632191,  0.4388022 ]]])

In [43]:
a4.reshape(4,2,2)

array([[[-0.09277332, -0.39922445],
        [-0.87079802,  0.97532473]],

       [[-0.09171193,  0.16879142],
        [-0.97528774, -1.20683175]],

       [[-1.12968683, -0.99997113],
        [ 1.3143284 , -0.2297609 ]],

       [[ 0.41114112, -0.46427738],
        [-0.61632191,  0.4388022 ]]])

In [44]:
a1

array(['4', '5', '6', '7', 'nagesh', '34.57', 'True'], dtype='<U32')

In [45]:
a1[0]

'4'

In [47]:
for i in a1:
    print(i)

4
5
6
7
nagesh
34.57
True


In [48]:
a1[2:6]

array(['6', '7', 'nagesh', '34.57'], dtype='<U32')

In [49]:
a1[::-1]

array(['True', '34.57', 'nagesh', '7', '6', '5', '4'], dtype='<U32')

In [53]:
a1[2:6:2]

array(['6', 'nagesh'], dtype='<U32')

In [54]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a2[0]

array([1, 2, 3])

In [59]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [60]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [61]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [64]:
a2[[0,1],[0,2]]

array([1, 6])

In [69]:
a5 = np.random.randint(2,90,(6,5))

In [71]:
a5

array([[ 6, 13, 86,  8, 36],
       [ 4, 38,  5, 62,  2],
       [ 2, 80, 80, 10, 19],
       [27,  4, 31, 43, 82],
       [11, 69, 79, 73, 22],
       [52, 61, 76, 37, 88]])

In [70]:
a5[a5>40]

array([86, 62, 80, 80, 43, 82, 69, 79, 73, 52, 61, 76, 88])

In [72]:
a5[0,1]

13

In [73]:
a5[0,1]=100

In [74]:
a5

array([[  6, 100,  86,   8,  36],
       [  4,  38,   5,  62,   2],
       [  2,  80,  80,  10,  19],
       [ 27,   4,  31,  43,  82],
       [ 11,  69,  79,  73,  22],
       [ 52,  61,  76,  37,  88]])

In [76]:
for i in a5:
    a5=a5+100


In [77]:
a5

array([[1206, 1300, 1286, 1208, 1236],
       [1204, 1238, 1205, 1262, 1202],
       [1202, 1280, 1280, 1210, 1219],
       [1227, 1204, 1231, 1243, 1282],
       [1211, 1269, 1279, 1273, 1222],
       [1252, 1261, 1276, 1237, 1288]])

In [81]:
a6 = np.random.randint(0,3,(3,3))

In [82]:
a7 = np.random.randint(0,3,(3,3))

In [83]:
a6

array([[1, 0, 2],
       [1, 2, 1],
       [1, 2, 0]])

In [84]:
a7

array([[2, 0, 2],
       [0, 0, 1],
       [0, 0, 2]])

In [85]:
a6*a7  # this is element to element multiplication

array([[2, 0, 4],
       [0, 0, 1],
       [0, 0, 0]])

In [87]:
a6@a7   # symball @ gives matrix multiplication

array([[2, 0, 6],
       [2, 0, 6],
       [2, 0, 4]])

In [88]:
a6+a7 # addition of matrixes

array([[3, 0, 4],
       [1, 2, 2],
       [1, 2, 2]])

In [89]:
a6-a7 # subtraction of matrixes

array([[-1,  0,  0],
       [ 1,  2,  0],
       [ 1,  2, -2]])

In [90]:
a6+100

array([[101, 100, 102],
       [101, 102, 101],
       [101, 102, 100]])

In [91]:
a6*2

array([[2, 0, 4],
       [2, 4, 2],
       [2, 4, 0]])

In [92]:
a6/0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12708\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12708\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [inf, inf, inf],
       [inf, inf, nan]])

In [93]:
a6

array([[1, 0, 2],
       [1, 2, 1],
       [1, 2, 0]])

In [94]:
a6**3

array([[1, 0, 8],
       [1, 8, 1],
       [1, 8, 0]], dtype=int32)

In [98]:
a8 = np.zeros((4,4))

In [99]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
a9 = np.ones((4,5))

In [102]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [105]:
a9 + np.array([1,2,3,4,5]) # row wise addition

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [110]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [112]:
 np.array([[1,2,3,4]]).T  # here T represent the transpose for array but for that purpose required 2D array

array([[1],
       [2],
       [3],
       [4]])

In [113]:
a6

array([[1, 0, 2],
       [1, 2, 1],
       [1, 2, 0]])

In [114]:
a6.T

array([[1, 1, 1],
       [0, 2, 2],
       [2, 1, 0]])

In [115]:
a5

array([[1206, 1300, 1286, 1208, 1236],
       [1204, 1238, 1205, 1262, 1202],
       [1202, 1280, 1280, 1210, 1219],
       [1227, 1204, 1231, 1243, 1282],
       [1211, 1269, 1279, 1273, 1222],
       [1252, 1261, 1276, 1237, 1288]])

In [116]:
np.sqrt(a6)

array([[1.        , 0.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 0.        ]])

In [117]:
np.exp(a6)

array([[2.71828183, 1.        , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 1.        ]])

In [119]:
np.log10(a5)

array([[3.08134731, 3.11394335, 3.10924097, 3.08206693, 3.09201847],
       [3.08062649, 3.09272064, 3.08098705, 3.10105935, 3.07990447],
       [3.07990447, 3.10720997, 3.10720997, 3.08278537, 3.08600371],
       [3.08884456, 3.08062649, 3.09025805, 3.09447113, 3.10788803],
       [3.08314414, 3.10346162, 3.10687054, 3.1048284 , 3.08707121],
       [3.09760433, 3.10071509, 3.10585067, 3.0923697 , 3.10991586]])

In [125]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [123]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [124]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.arange(0,10,2.5)  # it excepts the floating point number 

array([0. , 2.5, 5. , 7.5])

In [127]:
np.linspace(2,3,num=50)  # 50 equal parts numbrs in between 2 and 3

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [128]:
np.linspace(2,3,num=50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [131]:
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [132]:
np.eye(5)  # unit array 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [140]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [139]:
!pip install cufflinks

In [141]:
 cf.go_offline()

In [148]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])
df

A         B         C
0   0.135774 -1.345695  0.664577
1  -1.863401  0.450168  0.193349
2   0.289991 -1.877860 -0.254906
3   0.393474 -1.114128 -2.310432
4   0.160965 -0.302049  0.269991
..       ...       ...       ...
95 -0.331159 -0.698574  1.235750
96 -1.102057  0.416340  1.478929
97 -2.307338 -0.566648 -1.317409
98 -0.638319  0.236243 -0.342634
99 -0.720257 -0.316688 -2.240573

[100 rows x 3 columns]

In [149]:
df.iplot()

In [151]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [152]:
df1

0
0   10
1   93
2   71
3   81
4   14
..  ..
95  22
96   6
97  95
98  45
99  33

[100 rows x 1 columns]

In [153]:
df1.iplot()

In [155]:
df.iplot(x='A',y='B',mode='markers')

In [158]:
df2 = sns.load_dataset('titanic')

In [160]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [161]:
df2.iplot(x='age', y='fare', mode = 'markers')

In [165]:
df2.iplot(x='age', y='pclass', mode = 'markers')

In [166]:
df2.iplot(x='fare', y='pclass', mode = 'markers')

In [167]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [168]:
df2.iplot( kind = 'bar', x = 'sex' ,y = 'survived')

In [173]:
df2.iplot( kind = 'area', x = 'sex' ,y = 'survived')